name: Run Discord Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Environment Variables
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}"
          echo "CHANNEL_ID=${{ secrets.CHANNEL_ID }}"
          echo "DROPBOX_REFRESH_TOKEN=${{ secrets.DROPBOX_REFRESH_TOKEN }}"
          echo "DROPBOX_APP_KEY=${{ secrets.DROPBOX_APP_KEY }}"
          echo "DROPBOX_APP_SECRET=${{ secrets.DROPBOX_APP_SECRET }}"
          echo "DROPBOX_FOLDER_PATH=${{ secrets.DROPBOX_FOLDER_PATH }}"

      - name: Run the bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_FOLDER_PATH: ${{ secrets.DROPBOX_FOLDER_PATH }}
        run: |
          python main.py
