name: Run Discord Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode Google Drive Credentials
        env:
          GOOGLE_DRIVE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS_BASE64 }}
        run: |
          echo $GOOGLE_DRIVE_CREDENTIALS_BASE64 | base64 --decode > credentials.json

      - name: Debug Environment Variables
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}"
          echo "CHANNEL_ID=${{ secrets.CHANNEL_ID }}"
          echo "GOOGLE_DRIVE_CREDENTIALS_BASE64 is set"
          echo "GOOGLE_DRIVE_FOLDER_ID=${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}"

      - name: Run the bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          GOOGLE_DRIVE_CREDENTIALS=credentials.json
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        run: |
          python main.py
